#!/bin/env lua

--[[
Uso: slinix press.slx
]]

function span_elements(line)	

	-- Backslash Escapes
	line = line:gsub("(\\%*)", "&code")
	-- todo

	-- html entities	
	-- toto

	-- double asterisks
	line = line:gsub("%*%*(%a+[^%*%*]*)%*%*", "<strong>%1</strong>")	
	-- double underscores
	line = line:gsub("__(%a+[^__]*)__", "<strong>%1</strong>")	
	-- single asterisks
	line = line:gsub("%*(%a+[^%*]*)%*", "<em>%1</em>")	
	-- single underscores
	line = line:gsub("_(%a+[^_]*)_", "<em>%1</em>")	

	-- code
	line = line:gsub("`([^`]*)`", "<code>%1</code>")	
	
	-- links
	line = line:gsub("%[([^%]]*)%]", "<a href=\"%1\">")

	-- image
	line = line:gsub("!%(([^%)]*)%)", "<img src=\"%1\">")	

	return line
end

function block_elements(line)
	line = line:gsub("^######(.*)", "<h6>%1</h6>")
	line = line:gsub("^#####(.*)", "<h5>%1</h5>")
	line = line:gsub("^####(.*)", "<h4>%1</h4>")
	line = line:gsub("^###(.*)", "<h3>%1</h3>")
	line = line:gsub("^##(.*)", "<h2>%1</h2>")
	line = line:gsub("^#(.*)", "<h1>%1</h1>")
	return line
end

function slinix(file)
	local START_DOCUMENT = 0
	local PARAGRAPH = 1
	local UNORDERED_LIST = 2	
	local ORDERED_LIST = 3
	local current_state = START_DOCUMENT

	for line in io.lines(file) do		
		isBlank = line == ""		
		isUnorderedListBullet = line:find("%* .+") 		
		isOrderedListBullet = line:find("%d+%. .+") 		

		if current_state == START_DOCUMENT then
			if isBlank then
				current_state = START_DOCUMENT
			elseif isUnorderedListBullet then
				current_state = UNORDERED_LIST				
				print "<p>"
				print "<ul>"
				print "<li>"
				print (span_elements(line:sub(3)))
				print "</li>"
			elseif isOrderedListBullet then
				current_state = ORDERED_LIST				
				print "<p>"
				print "<ol>"
				print "<li>"
				print (span_elements(line:sub(3)))
				print "</li>"
			else 
				current_state = PARAGRAPH
				print "<p>"
				print (span_elements(line))
			end
		elseif current_state == PARAGRAPH then
			if isBlank then
				current_state = START_DOCUMENT
				print "</p>"
			elseif isUnorderedListBullet then
				current_state = UNORDERED_LIST
				print "</p>"
				print "<p>"
				print "<ul>"
				print "<li>"
				print (span_elements(line:sub(3)))
				print "</li>"
			elseif isOrderedListBullet then
				current_state = ORDERED_LIST
				print "</p>"
				print "<p>"
				print "<ol>"
				print "<li>"
				print (span_elements(line:sub(3)))
				print "</li>"
			else
				print (span_elements(line))
			end
		elseif current_state == UNORDERED_LIST then
			if isBlank then
				current_state = UNORDERED_LIST
			elseif isUnorderedListBullet then
				current_state = UNORDERED_LIST
				print "<li>"
				print (span_elements(line:sub(3)))
				print "</li>"
			elseif isOrderedListBullet then
				current_state = ORDERED_LIST
				print "</ul>"
				print "</p>"
				print "<p>"
				print "<ol>"
				print "<li>"				
				print (span_elements(line:sub(3)))
				print "</li>"
			else
				current_state = PARAGRAPH
				print "</ul>"
				print "</p>"
				print "<p>"
				print (span_elements(line))
			end
		elseif current_state == ORDERED_LIST then
			if isBlank then
				current_state = ORDERED_LIST
			elseif isUnorderedListBullet then
				current_state = UNORDERED_LIST
				print "</ol>"
				print "</p>"
				print "<p>"
				print "<ul>"
				print "<li>"				
				print (span_elements(line:sub(3)))
				print "</li>"				
			elseif isOrderedListBullet then
				current_state = ORDERED_LIST
				print "<li>"
				print (span_elements(line:sub(3)))
				print "</li>"
			else
				current_state = PARAGRAPH
				print "</ol>"
				print "</p>"
				print "<p>"
				print (span_elements(line))
			end
		end
	end		
end

slinix(arg[1])