#!/bin/env lua

--[[
Uso: slinix press.slx
]]

function span_elements(line)	

	-- Backslash Escapes
	line = line:gsub("(\\%*)", "&code")
	-- todo

	-- html entities	
	-- toto

	-- double asterisks
	line = line:gsub("%*%*(%a+[^%*%*]*)%*%*", "<strong>%1</strong>")	
	-- double underscores
	line = line:gsub("__(%a+[^__]*)__", "<strong>%1</strong>")	
	-- single asterisks
	line = line:gsub("%*(%a+[^%*]*)%*", "<em>%1</em>")	
	-- single underscores
	line = line:gsub("_(%a+[^_]*)_", "<em>%1</em>")	

	-- code
	line = line:gsub("`([^`]*)`", "<code>%1</code>")	
	
	-- links
	line = line:gsub("%[([^%]]*)%]", "<a href=\"%1\">")

	-- image
	line = line:gsub("!%(([^%)]*)%)", "<img src=\"%1\">")	

	return line
end

function block_elements(line)
	line = line:gsub("^######(.*)", "<h6>%1</h6>")
	line = line:gsub("^#####(.*)", "<h5>%1</h5>")
	line = line:gsub("^####(.*)", "<h4>%1</h4>")
	line = line:gsub("^###(.*)", "<h3>%1</h3>")
	line = line:gsub("^##(.*)", "<h2>%1</h2>")
	line = line:gsub("^#(.*)", "<h1>%1</h1>")
	return line
end

function slinix(file)
	local START_DOCUMENT = 0;
	local PARAGRAPH = 1;
	local current_state = START_DOCUMENT	

	for line in io.lines(file) do
		if current_state == START_DOCUMENT then
			if line then				
				current_state = PARAGRAPH
				print "<p>"
			end
		elseif current_state == PARAGRAPH then
			if line == "" then				
				print "</p>"
				current_state = START_DOCUMENT
			end
		end	

		if line then print(span_elements(line)) end
	end

	if current_state == PARAGRAPH then
		print "</p>"
	end
end
--[[
print(span_elements("*single asterisks*"))
print(span_elements("_single underscores_"))
print(span_elements("**double asterisks**"))
print(span_elements("__double underscores__"))
print(span_elements("Use the `printf()` function."))
print(span_elements("!(/path/to/img.jpg)"))
print(span_elements("[http://example.com/]"))

print(block_elements("# This is an H1"))
print(block_elements("## This is an H2"))
print(block_elements("### This is an H3"))
print(block_elements("#### This is an H4"))
print(block_elements("##### This is an H5"))
print(block_elements("###### This is an H6"))	

print(block_elements("A ###### This is not an H6"))	
]]

slinix(arg[1])